package main;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import java.sql.*;
import java.io.*;
import java.sql.Driver;
import java.sql.Connection;
import javax.swing.table.*;
import static main.Interface.keyboard;
import static main.Interface.register;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ashleykim
 */
public class posGUI extends javax.swing.JFrame {

    public static Register register = new Register();
    /**
     * Creates new form posGUI
     */
    public posGUI() {
        initComponents();
    
        //DBManager db= new DBManager();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        loginPanel = new javax.swing.JPanel();
        usernameTextField = new javax.swing.JTextField();
        passwordTextField = new javax.swing.JPasswordField();
        usernameLabel = new javax.swing.JLabel();
        loginButton = new javax.swing.JButton();
        passwordLabel = new javax.swing.JLabel();
        newEmployeeButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        menuPanel = new javax.swing.JPanel();
        saleButton = new javax.swing.JButton();
        rentalButton = new javax.swing.JButton();
        returnButton = new javax.swing.JButton();
        menuHeaderLabel = new javax.swing.JLabel();
        Logout = new javax.swing.JButton();
        salePanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ProcessSaleTable = new javax.swing.JTable();
        processSaleLabel = new javax.swing.JLabel();
        itemIDLabel = new javax.swing.JLabel();
        quantityLabel = new javax.swing.JLabel();
        itemIDTextField = new javax.swing.JTextField();
        quantityTextField = new javax.swing.JTextField();
        addToCartButton = new javax.swing.JButton();
        checkOutButton = new javax.swing.JButton();
        rentalPanel = new javax.swing.JPanel();
        RentalLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        rentalTable = new javax.swing.JTable();
        rentalItemIDLabel = new javax.swing.JLabel();
        rentalQuantityLabel = new javax.swing.JLabel();
        rentalDurationLabel = new javax.swing.JLabel();
        rentalItemIDTextField = new javax.swing.JTextField();
        rentalQuantityTextField = new javax.swing.JTextField();
        rentalDurationTextField = new javax.swing.JTextField();
        rentalAddToCartButton = new javax.swing.JButton();
        rentalCheckOutButton = new javax.swing.JButton();
        returnPanel = new javax.swing.JPanel();
        returnLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        returnTable = new javax.swing.JTable();
        returnItemIDLabel = new javax.swing.JLabel();
        returnQuantityLabel = new javax.swing.JLabel();
        returnDurationLabel = new javax.swing.JLabel();
        returnItemIDTextField = new javax.swing.JTextField();
        returnQuantityTextField = new javax.swing.JTextField();
        returnDurationTextField = new javax.swing.JTextField();
        returnAddToCartButton = new javax.swing.JButton();
        returnCheckOutButton = new javax.swing.JButton();
        checkOutPanel = new javax.swing.JPanel();
        checkOutLabel = new javax.swing.JLabel();
        subtotalLabel = new javax.swing.JLabel();
        taxLabel = new javax.swing.JLabel();
        totalLabel = new javax.swing.JLabel();
        subtotalTextField = new javax.swing.JTextField();
        taxTextField = new javax.swing.JTextField();
        totalTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        amountPaidTextField = new javax.swing.JTextField();
        payButton = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        checkoutTable = new javax.swing.JTable();
        receiptPanel = new javax.swing.JPanel();
        receiptTitle = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        changeTextField = new javax.swing.JTextField();
        homeButton = new javax.swing.JButton();
        transactionsLabel = new javax.swing.JLabel();
        newEmployeePanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        submitButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        newUserTextField = new javax.swing.JTextField();
        levelTextField = new javax.swing.JTextField();
        nameTextField = new javax.swing.JTextField();
        userTextField = new javax.swing.JTextField();
        noAccessLabel = new javax.swing.JLabel();
        passTextField = new javax.swing.JTextField();
        newPassTextField = new javax.swing.JTextField();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        usernameLabel.setFont(new java.awt.Font("Nanum Gothic", 0, 14)); // NOI18N
        usernameLabel.setText("Username:");

        loginButton.setFont(new java.awt.Font("Nanum Gothic", 0, 14)); // NOI18N
        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        passwordLabel.setFont(new java.awt.Font("Nanum Gothic", 0, 14)); // NOI18N
        passwordLabel.setText("Password:");

        newEmployeeButton.setFont(new java.awt.Font("Nanum Gothic", 0, 14)); // NOI18N
        newEmployeeButton.setText("New Employee");
        newEmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newEmployeeButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Nanum Gothic", 0, 18)); // NOI18N
        jLabel1.setText("Welcome to posSquared");

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newEmployeeButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(loginPanelLayout.createSequentialGroup()
                            .addComponent(usernameLabel)
                            .addGap(50, 50, 50)
                            .addComponent(usernameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
                        .addGroup(loginPanelLayout.createSequentialGroup()
                            .addComponent(passwordLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(passwordTextField))))
                .addGap(65, 65, 65))
        );

        loginPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {passwordTextField, usernameTextField});

        loginPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {loginButton, newEmployeeButton});

        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usernameLabel))
                        .addGap(26, 26, 26)
                        .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(passwordLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(newEmployeeButton)
                .addGap(27, 27, 27))
        );

        getContentPane().add(loginPanel, "card2");

        saleButton.setFont(new java.awt.Font("Nanum Gothic", 0, 14)); // NOI18N
        saleButton.setText("Sale");
        saleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saleButtonActionPerformed(evt);
            }
        });

        rentalButton.setFont(new java.awt.Font("Nanum Gothic", 0, 14)); // NOI18N
        rentalButton.setText("Rental");
        rentalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentalButtonActionPerformed(evt);
            }
        });

        returnButton.setFont(new java.awt.Font("Nanum Gothic", 0, 14)); // NOI18N
        returnButton.setText("Return");
        returnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnButtonActionPerformed(evt);
            }
        });

        menuHeaderLabel.setFont(new java.awt.Font("Nanum Gothic", 0, 18)); // NOI18N
        menuHeaderLabel.setText("Menu:");

        Logout.setFont(new java.awt.Font("Nanum Gothic", 0, 14)); // NOI18N
        Logout.setText("Logout");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(saleButton)
                    .addComponent(rentalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(returnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Logout))
                .addContainerGap(96, Short.MAX_VALUE))
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(menuHeaderLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menuPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Logout, rentalButton, returnButton, saleButton});

        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(menuHeaderLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(saleButton)
                .addGap(38, 38, 38)
                .addComponent(rentalButton)
                .addGap(39, 39, 39)
                .addComponent(returnButton)
                .addGap(42, 42, 42)
                .addComponent(Logout)
                .addGap(15, 15, 15))
        );

        getContentPane().add(menuPanel, "card3");

        ProcessSaleTable.setFont(new java.awt.Font("Nanum Gothic", 0, 14)); // NOI18N
        ProcessSaleTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Quantity", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(ProcessSaleTable);

        processSaleLabel.setFont(new java.awt.Font("Nanum Gothic", 0, 18)); // NOI18N
        processSaleLabel.setText("Process Sale");

        itemIDLabel.setFont(new java.awt.Font("Nanum Gothic", 0, 14)); // NOI18N
        itemIDLabel.setText("Item ID:");

        quantityLabel.setFont(new java.awt.Font("Nanum Gothic", 0, 14)); // NOI18N
        quantityLabel.setText("Quantity:");

        addToCartButton.setFont(new java.awt.Font("Nanum Gothic", 0, 14)); // NOI18N
        addToCartButton.setText("Add to Cart");
        addToCartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToCartButtonActionPerformed(evt);
            }
        });

        checkOutButton.setFont(new java.awt.Font("Nanum Gothic", 0, 14)); // NOI18N
        checkOutButton.setText("Check Out");
        checkOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkOutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout salePanelLayout = new javax.swing.GroupLayout(salePanel);
        salePanel.setLayout(salePanelLayout);
        salePanelLayout.setHorizontalGroup(
            salePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(salePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(salePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(salePanelLayout.createSequentialGroup()
                        .addGroup(salePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(processSaleLabel))
                        .addContainerGap(64, Short.MAX_VALUE))
                    .addGroup(salePanelLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(salePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(itemIDLabel)
                            .addComponent(quantityLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(salePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(itemIDTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(quantityTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57))))
            .addGroup(salePanelLayout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addGroup(salePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkOutButton)
                    .addComponent(addToCartButton))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        salePanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {addToCartButton, checkOutButton});

        salePanelLayout.setVerticalGroup(
            salePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(salePanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(processSaleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(salePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itemIDLabel)
                    .addComponent(itemIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(salePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantityLabel)
                    .addComponent(quantityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addToCartButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkOutButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(salePanel, "card4");

        RentalLabel.setFont(new java.awt.Font("Nanum Gothic", 0, 14)); // NOI18N
        RentalLabel.setText("Return");

        rentalTable.setFont(new java.awt.Font("Nanum Gothic", 0, 14)); // NOI18N
        rentalTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Quantity", "Duration"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(rentalTable);
        if (rentalTable.getColumnModel().getColumnCount() > 0) {
            rentalTable.getColumnModel().getColumn(0).setResizable(false);
            rentalTable.getColumnModel().getColumn(1).setResizable(false);
            rentalTable.getColumnModel().getColumn(2).setResizable(false);
        }

        rentalItemIDLabel.setFont(new java.awt.Font("Nanum Gothic", 0, 14)); // NOI18N
        rentalItemIDLabel.setText("Item ID:");

        rentalQuantityLabel.setFont(new java.awt.Font("Nanum Gothic", 0, 14)); // NOI18N
        rentalQuantityLabel.setText("Quantity:");

        rentalDurationLabel.setFont(new java.awt.Font("Nanum Gothic", 0, 14)); // NOI18N
        rentalDurationLabel.setText("Duration:");

        rentalAddToCartButton.setFont(new java.awt.Font("Nanum Gothic", 0, 14)); // NOI18N
        rentalAddToCartButton.setText("Add to Cart");
        rentalAddToCartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentalAddToCartButtonActionPerformed(evt);
            }
        });

        rentalCheckOutButton.setFont(new java.awt.Font("Nanum Gothic", 0, 14)); // NOI18N
        rentalCheckOutButton.setText("Checkout");
        rentalCheckOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentalCheckOutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout rentalPanelLayout = new javax.swing.GroupLayout(rentalPanel);
        rentalPanel.setLayout(rentalPanelLayout);
        rentalPanelLayout.setHorizontalGroup(
            rentalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rentalPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(rentalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RentalLabel)
                    .addGroup(rentalPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(rentalPanelLayout.createSequentialGroup()
                        .addGroup(rentalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(rentalPanelLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(rentalItemIDLabel)
                                .addGap(55, 55, 55))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rentalPanelLayout.createSequentialGroup()
                                .addGroup(rentalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(rentalQuantityLabel)
                                    .addComponent(rentalDurationLabel))
                                .addGap(47, 47, 47)))
                        .addGroup(rentalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(rentalPanelLayout.createSequentialGroup()
                                .addComponent(rentalItemIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(rentalAddToCartButton))
                            .addGroup(rentalPanelLayout.createSequentialGroup()
                                .addGroup(rentalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rentalDurationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rentalQuantityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(rentalCheckOutButton)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        rentalPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {rentalDurationTextField, rentalItemIDTextField, rentalQuantityTextField});

        rentalPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {rentalAddToCartButton, rentalCheckOutButton});

        rentalPanelLayout.setVerticalGroup(
            rentalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rentalPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(RentalLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(rentalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rentalItemIDLabel)
                    .addComponent(rentalItemIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rentalAddToCartButton))
                .addGroup(rentalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rentalPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(rentalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rentalQuantityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rentalQuantityLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(rentalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rentalDurationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rentalDurationLabel)))
                    .addGroup(rentalPanelLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(rentalCheckOutButton)))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        getContentPane().add(rentalPanel, "card5");

        returnLabel.setFont(new java.awt.Font("Nanum Gothic", 0, 18)); // NOI18N
        returnLabel.setText("Return");

        returnTable.setFont(new java.awt.Font("Nanum Gothic", 0, 14)); // NOI18N
        returnTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jScrollPane3.setViewportView(returnTable);

        returnItemIDLabel.setFont(new java.awt.Font("Nanum Gothic", 0, 14)); // NOI18N
        returnItemIDLabel.setText("Item ID:");

        returnQuantityLabel.setFont(new java.awt.Font("Nanum Gothic", 0, 14)); // NOI18N
        returnQuantityLabel.setText("Quantity:");

        returnDurationLabel.setFont(new java.awt.Font("Nanum Gothic", 0, 14)); // NOI18N
        returnDurationLabel.setText("Duration:");

        returnAddToCartButton.setFont(new java.awt.Font("Nanum Gothic", 0, 14)); // NOI18N
        returnAddToCartButton.setText("Add to Cart");
        returnAddToCartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnAddToCartButtonActionPerformed(evt);
            }
        });

        returnCheckOutButton.setFont(new java.awt.Font("Nanum Gothic", 0, 14)); // NOI18N
        returnCheckOutButton.setText("Checkout");
        returnCheckOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnCheckOutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout returnPanelLayout = new javax.swing.GroupLayout(returnPanel);
        returnPanel.setLayout(returnPanelLayout);
        returnPanelLayout.setHorizontalGroup(
            returnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(returnPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(returnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(returnLabel)
                    .addGroup(returnPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(returnPanelLayout.createSequentialGroup()
                        .addGroup(returnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(returnPanelLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(returnItemIDLabel)
                                .addGap(55, 55, 55))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, returnPanelLayout.createSequentialGroup()
                                .addGroup(returnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(returnDurationLabel)
                                    .addComponent(returnQuantityLabel))
                                .addGap(47, 47, 47)))
                        .addGroup(returnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(returnPanelLayout.createSequentialGroup()
                                .addComponent(returnItemIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(returnAddToCartButton))
                            .addGroup(returnPanelLayout.createSequentialGroup()
                                .addGroup(returnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(returnDurationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(returnQuantityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(returnCheckOutButton)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        returnPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {returnDurationTextField, returnItemIDTextField, returnQuantityTextField});

        returnPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {returnAddToCartButton, returnCheckOutButton});

        returnPanelLayout.setVerticalGroup(
            returnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(returnPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(returnLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(returnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(returnItemIDLabel)
                    .addComponent(returnItemIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(returnAddToCartButton))
                .addGroup(returnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(returnPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(returnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(returnQuantityLabel)
                            .addComponent(returnQuantityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(returnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(returnDurationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(returnDurationLabel)))
                    .addGroup(returnPanelLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(returnCheckOutButton)))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        getContentPane().add(returnPanel, "card5");

        checkOutLabel.setText("Checkout");

        subtotalLabel.setText("Subtotal:");

        taxLabel.setText("Tax:");

        totalLabel.setText("Total:");

        jLabel2.setText("Please enter an amount to pay:");

        payButton.setText("Pay");
        payButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payButtonActionPerformed(evt);
            }
        });

        checkoutTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Quantity", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(checkoutTable);

        javax.swing.GroupLayout checkOutPanelLayout = new javax.swing.GroupLayout(checkOutPanel);
        checkOutPanel.setLayout(checkOutPanelLayout);
        checkOutPanelLayout.setHorizontalGroup(
            checkOutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkOutPanelLayout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(checkOutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkOutLabel)
                    .addGroup(checkOutPanelLayout.createSequentialGroup()
                        .addGroup(checkOutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(subtotalLabel)
                            .addComponent(taxLabel)
                            .addComponent(totalLabel)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(checkOutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(subtotalTextField)
                            .addComponent(taxTextField)
                            .addComponent(totalTextField)
                            .addComponent(amountPaidTextField)
                            .addComponent(payButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        checkOutPanelLayout.setVerticalGroup(
            checkOutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkOutPanelLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(checkOutLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(checkOutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subtotalLabel)
                    .addComponent(subtotalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(checkOutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(taxLabel)
                    .addComponent(taxTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(checkOutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totalLabel)
                    .addComponent(totalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(checkOutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(amountPaidTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(payButton)
                .addGap(8, 8, 8))
        );

        getContentPane().add(checkOutPanel, "card7");

        receiptTitle.setText("Receipt");

        jLabel4.setText("Change:");

        homeButton.setText("Return to Main Menu");
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout receiptPanelLayout = new javax.swing.GroupLayout(receiptPanel);
        receiptPanel.setLayout(receiptPanelLayout);
        receiptPanelLayout.setHorizontalGroup(
            receiptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(receiptPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(receiptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(transactionsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(receiptTitle)
                    .addGroup(receiptPanelLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(27, 27, 27)
                        .addGroup(receiptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(homeButton)
                            .addComponent(changeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        receiptPanelLayout.setVerticalGroup(
            receiptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(receiptPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(receiptTitle)
                .addGap(18, 18, 18)
                .addComponent(transactionsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(receiptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(changeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(homeButton)
                .addContainerGap())
        );

        getContentPane().add(receiptPanel, "card8");

        jLabel3.setFont(new java.awt.Font("Nanum Gothic", 0, 14)); // NOI18N
        jLabel3.setText("Create a New Employee");

        jLabel5.setFont(new java.awt.Font("Nanum Gothic", 0, 14)); // NOI18N
        jLabel5.setText("Your Username:");

        jLabel6.setFont(new java.awt.Font("Nanum Gothic", 0, 14)); // NOI18N
        jLabel6.setText("Your Password:");

        jLabel7.setFont(new java.awt.Font("Nanum Gothic", 0, 14)); // NOI18N
        jLabel7.setText("New Username:");

        jLabel8.setFont(new java.awt.Font("Nanum Gothic", 0, 14)); // NOI18N
        jLabel8.setText("New Password:");

        jLabel9.setFont(new java.awt.Font("Nanum Gothic", 0, 14)); // NOI18N
        jLabel9.setText("Security Level for New Employee:");

        jLabel10.setFont(new java.awt.Font("Nanum Gothic", 0, 14)); // NOI18N
        jLabel10.setText("Employee Name:");

        submitButton.setFont(new java.awt.Font("Nanum Gothic", 0, 14)); // NOI18N
        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        cancelButton.setFont(new java.awt.Font("Nanum Gothic", 0, 14)); // NOI18N
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout newEmployeePanelLayout = new javax.swing.GroupLayout(newEmployeePanel);
        newEmployeePanel.setLayout(newEmployeePanelLayout);
        newEmployeePanelLayout.setHorizontalGroup(
            newEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newEmployeePanelLayout.createSequentialGroup()
                .addGroup(newEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newEmployeePanelLayout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jLabel3))
                    .addGroup(newEmployeePanelLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(newEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(newEmployeePanelLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nameTextField))
                            .addComponent(jLabel9)
                            .addGroup(newEmployeePanelLayout.createSequentialGroup()
                                .addGroup(newEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(newEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(newUserTextField)
                                    .addComponent(userTextField)
                                    .addComponent(passTextField)
                                    .addComponent(newPassTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(newEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(newEmployeePanelLayout.createSequentialGroup()
                                .addComponent(levelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(newEmployeePanelLayout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addComponent(noAccessLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))))
                    .addGroup(newEmployeePanelLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(submitButton)
                        .addGap(66, 66, 66)
                        .addComponent(cancelButton)))
                .addContainerGap())
        );
        newEmployeePanelLayout.setVerticalGroup(
            newEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newEmployeePanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel3)
                .addGap(21, 21, 21)
                .addGroup(newEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(newEmployeePanelLayout.createSequentialGroup()
                        .addGroup(newEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(userTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(newEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(passTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(newEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(newUserTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(newEmployeePanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(noAccessLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(newEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(newPassTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(newEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(levelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(newEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(newEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitButton)
                    .addComponent(cancelButton))
                .addGap(19, 19, 19))
        );

        getContentPane().add(newEmployeePanel, "card9");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:
        String username= usernameTextField.getText();
        String password= new String (passwordTextField.getPassword()); 
        /*logOn(username, password);
            loginPanel.setVisible(false);
            menuPanel.setVisible(true);
        */
        
  
        String sql = "{?=call RECORDSYSTEMLOGONATTEMPT(?,?)}";
        int value=-1;
      try{
      java.sql.CallableStatement statement = DBManager.getConnection().prepareCall(sql);
      statement.registerOutParameter(1, java.sql.Types.INTEGER);      
      statement.setString(2, username);
      statement.setString(3, password);
      statement.execute();
      //System.out.println("here.");
      value = statement.getInt(1);
    }catch(Exception e){
      System.out.println("Something random happened:"+e);
      DBManager.closeConnection();
    }
    
    if(value > 1){
      loginPanel.setVisible(false);
      menuPanel.setVisible(true);
    }
    else{ 
      //return false;
       System.out.print("incorrect username/password combination");
    }
        
        
    }//GEN-LAST:event_loginButtonActionPerformed

    private void saleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saleButtonActionPerformed
        // TODO add your handling code here:
        menuPanel.setVisible(false);
        salePanel.setVisible(true);
    }//GEN-LAST:event_saleButtonActionPerformed

    private void addToCartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToCartButtonActionPerformed
        // TODO add your handling code here:
        register.makeOrder('S');
        System.out.println(register.order());
        int id = Integer.parseInt(itemIDTextField.getText());
        int quan = Integer.parseInt(quantityTextField.getText());
        register.order().addLineItem(register.getProduct(id), quan,0);
        Integer[] row = {id, quan, (int)register.getProduct(id).getPrice() * quan};//price?
        DefaultTableModel model = (DefaultTableModel)ProcessSaleTable.getModel();
        model.addRow(row);
    
        // ADD SALES TO TABLE
        
        //check to see if ID is in the database**
     
    
    }//GEN-LAST:event_addToCartButtonActionPerformed

    private void rentalCheckOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentalCheckOutButtonActionPerformed
        // TODO add your handling code here:
        rentalPanel.setVisible(false);
        checkOutPanel.setVisible(true);
        checkOutPanel.add(checkOutLabel);
        checkOutPanel.add(rentalTable);
        rentalTable.setVisible(true);
        double subtotal = register.order().getSubtotal();
        subtotalTextField.setText(Double.toString(subtotal));
        double total = subtotal * register.TAXRATE;
        double tax = total - subtotal;
        totalTextField.setText(Double.toString(total));
        taxTextField.setText(Double.toString(tax));
        
    }//GEN-LAST:event_rentalCheckOutButtonActionPerformed

    private void returnCheckOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnCheckOutButtonActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_returnCheckOutButtonActionPerformed

    private void rentalAddToCartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentalAddToCartButtonActionPerformed
        // TODO add your handling code here:
        register.makeOrder('R');
        System.out.println(register.order());
        int id = Integer.parseInt(rentalItemIDTextField.getText());
        int quan = Integer.parseInt(rentalQuantityTextField.getText());
        int duration = Integer.parseInt(rentalDurationTextField.getText());
        register.order().addLineItem(register.getProduct(id), quan, 0);
        Integer[] row = {id, quan, duration};
        DefaultTableModel model = (DefaultTableModel)rentalTable.getModel();
        model.addRow(row);
        
    }//GEN-LAST:event_rentalAddToCartButtonActionPerformed

    private void returnAddToCartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnAddToCartButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_returnAddToCartButtonActionPerformed

    private void rentalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentalButtonActionPerformed
        // TODO add your handling code here:
        menuPanel.setVisible(false);
        rentalPanel.setVisible(true);
    }//GEN-LAST:event_rentalButtonActionPerformed

    private void returnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButtonActionPerformed
        // TODO add your handling code here:
        menuPanel.setVisible(false);
        returnPanel.setVisible(true);
    }//GEN-LAST:event_returnButtonActionPerformed

    private void checkOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkOutButtonActionPerformed
        // TODO add your handling code here:
        salePanel.setVisible(false);
        checkOutPanel.setVisible(true);
        checkOutPanel.add(checkOutLabel);
       // checkOutPanel.add(ProcessSaleTable);
        //ProcessSaleTable.setVisible(true);
        double subtotal = register.order().getSubtotal();
        subtotalTextField.setText(Double.toString(subtotal));
        double total = subtotal * register.TAXRATE;
        double tax = total - subtotal;
        totalTextField.setText(Double.toString(total));
        taxTextField.setText(Double.toString(tax));
        //ProcessSaleTable.setVisible(false);
        
        //salePanel.add(ProcessSaleTable);
      
    
    
    }//GEN-LAST:event_checkOutButtonActionPerformed

    private void payButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payButtonActionPerformed
        // TODO add your handling code here:
        checkOutPanel.setVisible(false);
        receiptPanel.setVisible(true);
        receiptPanel.add(receiptTitle);
        //checkoutTable= ProcessSaleTable;
        //receiptPanel.add(ProcessSaleTable);
        transactionsLabel.setText(register.order().toString());
    //Store transaction in the database
        double amountPaid = Integer.parseInt(amountPaidTextField.getText());
        double change = amountPaid - register.order().getSubtotal()*register.TAXRATE;
        changeTextField.setText(Double.toString(change));
        
    }//GEN-LAST:event_payButtonActionPerformed

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)ProcessSaleTable.getModel();
        while(ProcessSaleTable.getRowCount() > 0)
        {
            model.removeRow(0);
        }
        DefaultTableModel model2 = (DefaultTableModel)rentalTable.getModel();
        while(rentalTable.getRowCount() > 0)
        {
            model2.removeRow(0);
        }
        DefaultTableModel model3 = (DefaultTableModel)returnTable.getModel();
        while(returnTable.getRowCount() > 0)
        {
            model3.removeRow(0);
        }
        
        itemIDTextField.setText("");
        quantityTextField.setText("");
        rentalItemIDTextField.setText("");
        rentalQuantityTextField.setText("");
        returnItemIDTextField.setText("");
        returnQuantityTextField.setText("");
        rentalDurationTextField.setText("");
        subtotalTextField.setText("");
        taxTextField.setText("");
        totalTextField.setText("");
        
        receiptPanel.setVisible(false);
        menuPanel.setVisible(true);
    }//GEN-LAST:event_homeButtonActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        // TODO add your handling code here:
        
        //logout(usernameTextField.getText());
    String sql = "{?=call RECORDSYSTEMLOGOUT(?)}";
    int value=-1;
    try{
      java.sql.CallableStatement statement = DBManager.getConnection().prepareCall(sql);
      statement.registerOutParameter(1, java.sql.Types.INTEGER);
      statement.setString(2, usernameTextField.getText());
      //System.out.println("here.");
      statement.execute();
      value = statement.getInt(1);
    }catch(Exception e){
      System.out.println("Something happened." + e);
      DBManager.closeConnection();
    }
    
    if(value == 0){
        menuPanel.setVisible(false);
        loginPanel.setVisible(true);
    }
        
        usernameTextField.setText("");
        passwordTextField.setText("");
    }//GEN-LAST:event_LogoutActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
        //String password= new String (passTextField.getPassword());
        //String newpassword= new String (newPassTextField.getPassword());
        if(!SystemAdmin.addNewUser(userTextField.getText(), passTextField.getText(), newUserTextField.getText(), newPassTextField.getText(), Integer.parseInt(levelTextField.getText()), nameTextField.getText()))
            noAccessLabel.setText("Access Denied");
        else{
            newEmployeePanel.setVisible(false);
            newPassTextField.setText("");
            newUserTextField.setText("");
            levelTextField.setText("");
            userTextField.setText("");
            passTextField.setText("");
            nameTextField.setText("");
            noAccessLabel.setText("");
            loginPanel.setVisible(true);
        }
    }//GEN-LAST:event_submitButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        newEmployeePanel.setVisible(false);
        noAccessLabel.setText("");
        newPassTextField.setText("");
        newUserTextField.setText("");
        levelTextField.setText("");
        userTextField.setText("");
        passTextField.setText("");
        nameTextField.setText("");
        loginPanel.setVisible(true);
        
        
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void newEmployeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newEmployeeButtonActionPerformed
        // TODO add your handling code here:
        loginPanel.setVisible(false);
        newEmployeePanel.setVisible(true);
    }//GEN-LAST:event_newEmployeeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(posGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(posGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(posGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(posGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new posGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Logout;
    private javax.swing.JTable ProcessSaleTable;
    private javax.swing.JLabel RentalLabel;
    private javax.swing.JButton addToCartButton;
    private javax.swing.JTextField amountPaidTextField;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField changeTextField;
    private javax.swing.JButton checkOutButton;
    private javax.swing.JLabel checkOutLabel;
    private javax.swing.JPanel checkOutPanel;
    private javax.swing.JTable checkoutTable;
    private javax.swing.JButton homeButton;
    private javax.swing.JLabel itemIDLabel;
    private javax.swing.JTextField itemIDTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField levelTextField;
    private javax.swing.JButton loginButton;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JLabel menuHeaderLabel;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JButton newEmployeeButton;
    private javax.swing.JPanel newEmployeePanel;
    private javax.swing.JTextField newPassTextField;
    private javax.swing.JTextField newUserTextField;
    private javax.swing.JLabel noAccessLabel;
    private javax.swing.JTextField passTextField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPasswordField passwordTextField;
    private javax.swing.JButton payButton;
    private javax.swing.JLabel processSaleLabel;
    private javax.swing.JLabel quantityLabel;
    private javax.swing.JTextField quantityTextField;
    private javax.swing.JPanel receiptPanel;
    private javax.swing.JLabel receiptTitle;
    private javax.swing.JButton rentalAddToCartButton;
    private javax.swing.JButton rentalButton;
    private javax.swing.JButton rentalCheckOutButton;
    private javax.swing.JLabel rentalDurationLabel;
    private javax.swing.JTextField rentalDurationTextField;
    private javax.swing.JLabel rentalItemIDLabel;
    private javax.swing.JTextField rentalItemIDTextField;
    private javax.swing.JPanel rentalPanel;
    private javax.swing.JLabel rentalQuantityLabel;
    private javax.swing.JTextField rentalQuantityTextField;
    private javax.swing.JTable rentalTable;
    private javax.swing.JButton returnAddToCartButton;
    private javax.swing.JButton returnButton;
    private javax.swing.JButton returnCheckOutButton;
    private javax.swing.JLabel returnDurationLabel;
    private javax.swing.JTextField returnDurationTextField;
    private javax.swing.JLabel returnItemIDLabel;
    private javax.swing.JTextField returnItemIDTextField;
    private javax.swing.JLabel returnLabel;
    private javax.swing.JPanel returnPanel;
    private javax.swing.JLabel returnQuantityLabel;
    private javax.swing.JTextField returnQuantityTextField;
    private javax.swing.JTable returnTable;
    private javax.swing.JButton saleButton;
    private javax.swing.JPanel salePanel;
    private javax.swing.JButton submitButton;
    private javax.swing.JLabel subtotalLabel;
    private javax.swing.JTextField subtotalTextField;
    private javax.swing.JLabel taxLabel;
    private javax.swing.JTextField taxTextField;
    private javax.swing.JLabel totalLabel;
    private javax.swing.JTextField totalTextField;
    private javax.swing.JLabel transactionsLabel;
    private javax.swing.JTextField userTextField;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JTextField usernameTextField;
    // End of variables declaration//GEN-END:variables
}
